#BNF+EMV2.0;

!grammar UserEval;
!start <Top>;

<Top>: <Move1> | <Move2> | <Move3> | <PickUp> | <Release> | <Perception> | <Grounding> | <Repeat> | stop | <Opening> | <Closing> | <Other> ;

<Front>: !optional(and) !optional(<Name>) !optional(could you) !optional(now) !optional(please)
<Back>: !optional(<Name) !optional(please);

<Move1>: <Front> !optional(<Move4>) !optional(<Modif>) (forward | forwards | backward | backwards | back | straight) !optional(<Modif>) <Back>; ;
<Move2>: <Front> !optional(<Move5>)  !optional(<Modif2>) !optional(to the) (left | right) !optional(<Modif2>) <Back>;
<Move3>: <Front> (turn back | turn one hundred eighty degrees | make a u turn | turn around) <Back>;

<Move4>: walk | go | move;
<Move5>: go | move | turn | rotate;


<Modif>: !optional(just) a !optional(little) bit | again;
<Modif2>: <Modif> | (thirty | sixty) degrees ;

<PickUp>: <Front> (take <Object> | take it | pick up <Object> | grasp <Object> | grasp it | pick it up) <Back>;

<Release>: <Front> ((release | put down) <Object> | put <Object> (down | on the floor | on the table)) <Back>;

<Object>: something | (the | a) !optional(<Colour>) (food can | object | cylinder) !optional(at your feet);

<Colour>: red | blue | green | yellow | white | black ;

<Perception>: what (can | do) you (see | perceive) | (can | do) you (see | perceive) <Object>;

<Grounding>: yes !optional(please) | no | exactly | ok ;

 <Other>: thanks !optional(<Name>) | thank you !optional(<Name>) | !optional(<Front2>) (correct | incorrect | wrong | right | perfect | great | good);
 
<Front2>: that's | that is | this is ;

<Repeat>: <Front> (do | repeat) (it | that) (again | once more | one more time) ;

<Opening>: (hi | hello ) <Name>;

<Closing>: (bye | goodbye) !optional(<Name>);

<Name>: robot | nao | lenny;