// =================================================================                                                                   
// Copyright (C) 2011-2013 Pierre Lison (plison@ifi.uio.no)                                                                            
//                                                                                                                                     
// This library is free software; you can redistribute it and/or                                                                       
// modify it under the terms of the GNU Lesser General Public License                                                                  
// as published by the Free Software Foundation; either version 2.1 of                                                                 
// the License, or (at your option) any later version.                                                                                 
//                                                                                                                                     
// This library is distributed in the hope that it will be useful, but                                                                 
// WITHOUT ANY WARRANTY; without even the implied warranty of                                                                          
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU                                                                    
// Lesser General Public License for more details.                                                                                     
//                                                                                                                                     
// You should have received a copy of the GNU Lesser General Public                                                                    
// License along with this program; if not, write to the Free Software                                                                 
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA                                                                           
// 02111-1307, USA.                                                                                                                    
// =================================================================                                                                   

package opendial.inputs;

import java.util.HashMap;
import java.util.Map;

import opendial.utils.Logger;

/**
 * Representation of an N-best List generated by a speech recogniser. 
 * The N-best list is made of a list of alternative utterances, each of which
 * is associated with a particular score or probability.
 *
 * @author  Pierre Lison (plison@ifi.uio.no)
 * @version $Date::                      $
 *
 */
public class NBestList implements Observation {

	// logger
	static Logger log = new Logger("NBestList", Logger.Level.NORMAL);
	
	// the list of alternative utterances, with their probability
	Map<String,Float> alternativeUtterances;
	
	
	/**
	 * Creates a new N-best list, with an empty list of utterances
	 */
	public NBestList() {
		alternativeUtterances = new HashMap<String,Float>();
	}
	
	
	/**
	 * Creates a new N-best list, with the given list of utterances
	 * 
	 * @param alternativeUtterances the utterances
	 */
	public NBestList(Map<String,Float> alternativeUtterances) {
		this.alternativeUtterances = alternativeUtterances;
	}
	
	
	/**
	 * Adds a new utterance (with associated probability) to the N-best list
	 * 
	 * @param utt the utterance
	 * @param prob the probability
	 */
	public void addUtterance(String utt, float prob) {
		alternativeUtterances.put(utt, prob);
	}
	
	
	/**
	 * Returns the list of utterances, together with their probabilities
	 * 
	 * @return the list of utterances
	 */
	public Map<String,Float> getUtterances() {
		return alternativeUtterances;
	}
	
	
	/**
	 * Returns a string representation of the N-best list
	 *
	 * @return
	 */
	@Override
	public String toString() {
		String str = "{";
		for (String utt : alternativeUtterances.keySet()) {
			str += "\"" + utt + "\" (" + alternativeUtterances.get(utt) + "), ";
		}
		return str.substring(0,str.length()-2) + "}";
	}
}
